### ISSUE TITLE
scan_for_known_people_from_db unable to detect faces

### ISSUE THREAD

**Issue by gould-ann** [samaritan-security/samaritan-backend#44]
method `scan_for_known_people_from_db()`'s encodings from database has an incorrect shape.
method `get_names_and_encodings_from_known()` needs to be changed because of this.
Because of this we can't correctly find `detected_faces`. 

Error trace from failed test from `script_tests` test `test_enncodings_from_db`
```
Error Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/anngould/IdeaProjects/samaritan-backend/tests/script_tests.py", line 25, in test_encodings_from_db
    foo = scan_for_known_people_from_db(self.encoded_encoding)
  File "/Users/anngould/IdeaProjects/samaritan-backend/FacialRecog.py", line 112, in scan_for_known_people_from_db
    detected_faces = face_recognition.compare_faces(all_encodings, npy_array)
  File "/Users/anngould/venv/samaritan-backend/lib/python3.7/site-packages/face_recognition/api.py", line 222, in compare_faces
    return list(face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)
  File "/Users/anngould/venv/samaritan-backend/lib/python3.7/site-packages/face_recognition/api.py", line 72, in face_distance
    return np.linalg.norm(face_encodings - face_to_compare, axis=1)
ValueError: operands could not be broadcast together with shapes (16,128) (120,90,3) 
```

**Comment by katebrune** [comment]
![image](https://user-images.githubusercontent.com/31379789/76170454-08bb6c00-6150-11ea-88af-2082497784e7.png)

i had that issue and figured it out, we need `np.fromstring(i['npy'], count=128)` to make sure the npy has array shape (,128) which is what compare_faces uses, so we can close this
